// 19 official Google PCA sample questions — verbatim text + answer keys + the
// official "Comentarios" explanations. Used for the base exam round; adaptive
// rounds use Claude-generated questions in the same shape.
export const QUESTIONS = [
  { id:1, topic:"Security & Compliance", case:"EHR Healthcare", type:"single",
    text:"Anonymous users from all over the world access a public health information website hosted in an on-premises EHR data center. The servers are older, and users complain about sluggish response times. There has been a recent increase of distributed denial-of-service attacks toward the website. The attacks always come from the same IP address ranges. You need to improve access latency and provide a security solution that will prevent the denial-of-service traffic from entering your VPC network. What should you do?",
    options:{
      A:"Deploy an external HTTP(S) load balancer, configure VPC firewall rules, and move the applications onto Compute Engine virtual machines.",
      B:"Deploy an external HTTP(S) load balancer, configure Google Cloud Armor, and move the application onto Compute Engine virtual machines.",
      C:"Containerize the application and move it into GKE. Create a GKE service to expose the pods within the cluster, and set up a GKE network policy.",
      D:"Containerize the application and move it into GKE. Create an internal load balancer to expose the pods outside the cluster, and configure Identity-Aware Proxy (IAP) for access."},
    correct:["B"],
    why:{ A:"Firewall rules do not block malicious traffic into a VPC; they block it at the VM level.",
      B:"The external HTTP(S) load balancer improves access latency and Cloud Armor can be configured to block the DDoS attack.",
      C:"A GKE service does not expose a set of pods outside of a cluster, and a GKE network policy only filters traffic between pods and services.",
      D:"A GKE internal load balancer will not load balance external traffic, and anonymous users need access, so IAP is not a fit."} },

  { id:2, topic:"Networking & Hybrid", case:"EHR Healthcare", type:"single",
    text:"EHR wants to connect one of their data centers to Google Cloud. The data center is in a remote location over 100 km from a Google-owned point of presence. They can't afford new hardware, but their existing firewall can accommodate future throughput growth. On-prem servers must talk to GKE resources; both on-prem and cloud use private RFC 1918 addresses; and the service provider says basic Internet connectivity is best-effort with no SLA. What should you recommend?",
    options:{ A:"Provision Carrier Peering.", B:"Provision a new Internet connection.",
      C:"Provision a Partner Interconnect connection.", D:"Provision a Dedicated Interconnect connection."},
    correct:["C"],
    why:{ A:"It does not give private IP addressing across the connection.",
      B:"An additional Internet connection will not provide RFC1918 communications by itself.",
      C:"It lowers latency by connecting directly to a partner network that is directly connected to Google, and lets the customer use the lower-bandwidth interfaces on their current firewall.",
      D:"Dedicated Interconnect would require the customer to buy new hardware to get a 10 Gig interface for their firewall."} },

  { id:3, topic:"Security & Compliance", case:"EHR Healthcare", type:"single",
    text:"A renowned research hospital requires that patient information stored in Cloud Storage buckets not leave the geographic areas in which the buckets are hosted. Sources have repeatedly tried to exfiltrate patient health information. You need to ensure that information stored in Cloud Storage buckets in the \"europe-west2\" region does not leave that area. What should you do?",
    options:{ A:"Encrypt the data in the application on-premises before it is stored in the \"europe-west2\" region.",
      B:"Enable VPC Service Controls, and create a service perimeter around the Cloud Storage resources.",
      C:"Assign the IAM \"storage.objectViewer\" role only to users and service accounts that need to use the data.",
      D:"Create an ACL that limits access to the bucket to authorized users only, and apply it to the buckets in \"europe-west2\"."},
    correct:["B"],
    why:{ A:"Encrypting the data does not stop data exfiltration.",
      B:"VPC Service Controls improves your ability to mitigate the risk of data exfiltration from Google Cloud services.",
      C:"IAM roles deal with identity-based access control, not context-aware perimeter security.",
      D:"Cloud Storage ACLs define who has access, but do not stop data exfiltration."} },

  { id:4, topic:"Security & Compliance", case:"EHR Healthcare", type:"single",
    text:"EHR sales employees are a remote workforce that needs to access web-based sales tools located in the EHR data center, regardless of location. EHR is retiring its VPN and you must move the web-based sales tools to a BeyondCorp access model. Each sales employee has a Google Workspace account used for SSO. What should you do?",
    options:{ A:"Create an Identity-Aware Proxy (IAP) connector that points to the sales tool application.",
      B:"Create a Google group for the sales tool application, and upgrade that group to a security group.",
      C:"Deploy an external HTTP(S) load balancer and create a custom Cloud Armor policy for the sales tool application.",
      D:"For every sales employee who needs access, give their Google Workspace user account the predefined AppEngine Viewer role."},
    correct:["A"],
    why:{ A:"The IAP connector allows you to manage access to HTTP-based apps outside of Google Cloud.",
      B:"Google groups by themselves do not grant access to an application nor move it to a BeyondCorp model.",
      C:"Cloud Armor does not authenticate or authorize application access.",
      D:"The application is installed in the datacenter, not in the App Engine environment."} },

  { id:5, topic:"Data & Analytics", case:"Mountkirk Games", type:"single",
    text:"You are the data compliance officer for Mountkirk Games and must protect customers' PII. Mountkirk wants to generate anonymized usage reports about their new game and delete PII data after a specific period of time. The solution should have minimal cost. What should you do?",
    options:{ A:"Archive audit logs in Cloud Storage, and manually generate reports.",
      B:"Write a Cloud Logging filter to export specific date ranges to Pub/Sub.",
      C:"Archive audit logs in BigQuery, and generate reports using Google Data Studio.",
      D:"Archive user logs on a locally attached persistent disk, and cat them to a text file for auditing."},
    correct:["C"],
    why:{ A:"Cloud Storage is an object store with no query language access for report generation.",
      B:"It does not address log storage for data retention.",
      C:"BigQuery allows easy querying for report generation, with low storage costs.",
      D:"Long-term storage in persistent disks is expensive."} },

  { id:6, topic:"Security & Compliance", case:"Mountkirk Games", type:"multi", pick:2,
    text:"Mountkirk Games wants their new gaming platform operated according to Google best practices. You want to verify Google-recommended security best practices are met while providing operations teams with the metrics they need. What should you do? (Choose two)",
    options:{ A:"Ensure that you aren't running privileged containers.",
      B:"Ensure that you are using obfuscated Tags on workloads.",
      C:"Ensure that you are using the native logging mechanisms.",
      D:"Ensure that workloads are not using securityContext to run as a group.",
      E:"Ensure that each cluster is running GKE metering so each team can be charged for their usage."},
    correct:["A","C"],
    why:{ A:"This is High Priority according to Google best practices.",
      B:"Tags should be readable and useful to the operations teams when working on the clusters.",
      C:"This is High Priority according to Google best practices.",
      D:"This may be required for some workloads.",
      E:"Although useful from a business process view, it won't impact the operations or security of the cluster."} },

  { id:7, topic:"Security & Compliance", case:"Mountkirk Games", type:"single",
    text:"You need to implement VPC Service Controls for Mountkirk Games. They want to allow Cloud Shell usage by their developers. Developers should not have full access to managed services. You need to balance these conflicting goals with the business requirements. What should you do?",
    options:{ A:"Use VPC Service Controls for the entire platform.",
      B:"Prioritize VPC Service Controls implementation over Cloud Shell usage for the entire platform.",
      C:"Include all developers in an access level associated with the service perimeter, and allow them to use Cloud Shell.",
      D:"Create a service perimeter around only the projects that handle sensitive data, and do not grant your developers access to it."},
    correct:["D"],
    why:{ A:"VPC Service Controls do not directly affect scaling of Google Cloud architecture.",
      B:"A security perimeter is not a business requirement, but rapid iteration is.",
      C:"It works but does not scale, and we do not want to give users this much access.",
      D:"VPC Service Controls protects data, and Cloud Shell facilitates rapid iteration of architecture changes."} },

  { id:8, topic:"SRE & Operations", case:"Mountkirk Games", type:"single",
    text:"Your new game running on Google Cloud is in public beta, and you want to design meaningful service level objectives (SLOs) before the game becomes generally available. What should you do?",
    options:{ A:"Define one SLO as 99.9% game server availability. Define the other SLO as less than 100-ms latency.",
      B:"Define one SLO as service availability that is the same as Google Cloud's availability. Define the other SLO as 100-ms latency.",
      C:"Define one SLO as 99% HTTP requests return the 2xx status code. Define the other SLO as 99% requests return within 100 ms.",
      D:"Define one SLO as total uptime of the game server within a week. Define the other SLO as the mean response time of all HTTP requests that are less than 100 ms."},
    correct:["C"],
    why:{ A:"It doesn't clearly define how to measure both the availability and latency.",
      B:"Google Cloud availability impacts customer availability but it is only one factor; availability could differ across products.",
      C:"It clearly defines the service level indicators and how to measure them.",
      D:"There is no objective for the server uptime."} },

  { id:9, topic:"Networking & Hybrid", case:"Helicopter Racing League", type:"single",
    text:"HRL wants you to help bring existing recorded video content to new fans in emerging regions. Considering HRL's business and technical requirements, what should you do?",
    options:{ A:"Serve the video content directly from a multi-region Cloud Storage bucket.",
      B:"Use Cloud CDN to cache the video content from HRL's existing public cloud provider.",
      C:"Use Apigee Edge to cache the video content from HRL's existing public cloud provider.",
      D:"Replicate the video content in GKE clusters in regions close to the fans."},
    correct:["B"],
    why:{ A:"A multi-region bucket does not serve all global areas with similar latency.",
      B:"Cloud CDN can cache data hosted on other cloud providers and supports large objects such as video.",
      C:"Apigee Edge is not designed to cache data larger than 512 KB.",
      D:"Replicating the video content introduces unnecessary complexity."} },

  { id:10, topic:"Security & Compliance", case:"TerramEarth", type:"single",
    text:"You are the data compliance officer for TerramEarth and must protect customers' PII, like credit card information. TerramEarth wants to personalize product recommendations for its large industrial customers. You need to respect data privacy and deliver a solution. What should you do?",
    options:{ A:"Use AutoML to provide data to the recommendation service.",
      B:"Process PII data on-premises to keep the private information more secure.",
      C:"Use the Cloud Data Loss Prevention (DLP) API to provide data to the recommendation service.",
      D:"Manually build, train, and test machine learning models to provide product recommendations anonymously."},
    correct:["C"],
    why:{ A:"AutoML does not inherently provide data de-identification.",
      B:"TerramEarth's requirements are to go into the cloud, not stay on-premises.",
      C:"Cloud DLP was specifically designed for this use case.",
      D:"Developing machine learning models is an excessive way to de-identify data."} },

  { id:11, topic:"Networking & Hybrid", case:null, type:"single",
    text:"You are designing a future-proof hybrid environment that will require network connectivity between Google Cloud and your on-premises environment. You want to ensure the Google Cloud environment is compatible with your on-premises networking environment. What should you do?",
    options:{ A:"Use the default VPC in your Google Cloud project. Use a Cloud VPN connection between on-premises and Google Cloud.",
      B:"Create a custom VPC in Google Cloud in auto mode. Use a Cloud VPN connection between on-premises and Google Cloud.",
      C:"Create a network plan for your VPC that uses CIDR ranges that overlap with your on-premises environment. Use a Cloud Interconnect connection.",
      D:"Create a network plan for your VPC that uses non-overlapping CIDR ranges with your on-premises environment. Use a Cloud Interconnect connection."},
    correct:["D"],
    why:{ A:"The default VPC has Auto Mode IP ranges, which has the same problem as answer C.",
      B:"With Auto Mode IP ranges there is no guarantee the ranges won't overlap with on-premises, now or in the future.",
      C:"To ensure correct routing, ranges cannot overlap between environments.",
      D:"This ensures your on-premises network is compatible with your Google Cloud VPC."} },

  { id:12, topic:"Data & Analytics", case:null, type:"single",
    text:"Your company wants to track whether someone is present in a reserved meeting room. There are 1000 meeting rooms across 5 offices on 3 continents. Each room has a motion sensor that reports status every second. The receiving infrastructure needs to account for devices that may have inconsistent connectivity. Which solution should you design?",
    options:{ A:"Have each device create a persistent connection to a Compute Engine instance and write messages to a custom application.",
      B:"Have devices poll for connectivity to Cloud SQL and insert the latest messages on a regular interval to a device-specific table.",
      C:"Have devices poll for connectivity to Pub/Sub and publish the latest messages on a regular interval to a shared topic for all devices.",
      D:"Have devices create a persistent connection to an App Engine application fronted by Cloud Endpoints, which ingests messages and writes them to Datastore."},
    correct:["C"],
    why:{ A:"A persistent connection does not handle the case where the device is disconnected.",
      B:"Cloud SQL is a regional relational database, not the best fit for sensor data; write frequency can exceed supported concurrent connections.",
      C:"Pub/Sub can handle the frequency of this data, and consumers can pull from the shared topic for further processing.",
      D:"A persistent connection does not handle the case where the device is disconnected."} },

  { id:13, topic:"Data & Analytics", case:null, type:"multi", pick:2,
    text:"Your company wants to try the cloud with low risk. They want to archive approximately 100 TB of log data to the cloud and test serverless analytics features, while also retaining that data as a long-term disaster recovery backup. Which two steps should they take? (Choose two)",
    options:{ A:"Load logs into BigQuery.", B:"Load logs into Cloud SQL.",
      C:"Import logs into Cloud Logging.", D:"Insert logs into Cloud Bigtable.",
      E:"Upload log files into Cloud Storage."},
    correct:["A","E"],
    why:{ A:"BigQuery is a serverless cloud data warehouse for analytics and supports the volume and analytics requirement.",
      B:"Cloud SQL does not support 100 TB and is a relational database, not the best fit for time-series log data.",
      C:"Cloud Logging is optimized for monitoring, error reporting, and debugging, not analytics queries.",
      D:"Cloud Bigtable is optimized for read-write latency and throughput, not analytics querying and reporting.",
      E:"Cloud Storage provides Coldline and Archive classes for long-term infrequent-access storage, supporting the DR backup requirement."} },

  { id:14, topic:"Networking & Hybrid", case:null, type:"single",
    text:"You set up an autoscaling managed instance group to serve web traffic. After configuring the group as a backend service to an HTTP(S) load balancer, you notice VM instances are being terminated and re-launched every minute. The instances have no public IP. You verified the appropriate web response from each instance using curl. You want to ensure the backend is configured correctly. What should you do?",
    options:{ A:"Ensure that a firewall rule exists to allow source traffic on HTTP/HTTPS to reach the load balancer.",
      B:"Assign a public IP to each instance, and configure a firewall rule to allow the load balancer to reach the instance public IP.",
      C:"Ensure that a firewall rule exists to allow load balancer health checks to reach the instances in the instance group.",
      D:"Create a tag on each instance with the name of the load balancer. Configure a firewall rule with the name of the load balancer as the source and the instance tag as the destination."},
    correct:["C"],
    why:{ A:"The issue to resolve is the VMs being terminated, not access to the load balancer.",
      B:"This introduces a security vulnerability without addressing the primary concern of the VM termination.",
      C:"Health check failures lead to a VM being marked unhealthy and terminated; since instances function properly, determine why the health check fails — it must be allowed to reach the instances.",
      D:"The source of the firewall rule that allows health-check access is defined IP ranges, not a named load balancer."} },

  { id:15, topic:"Networking & Hybrid", case:null, type:"single",
    text:"Your organization has a 3-tier web app deployed in the same VPC. Each tier (web, API, database) scales independently. Traffic should flow web → API → database. Traffic should NOT flow between the web and the database tier. How should you configure the network with minimal steps?",
    options:{ A:"Add each tier to a different subnetwork.",
      B:"Set up software-based firewalls on individual VMs.",
      C:"Add tags to each tier and set up routes to allow the desired traffic flow.",
      D:"Add tags to each tier and set up firewall rules to allow the desired traffic flow."},
    correct:["D"],
    why:{ A:"The subnetwork alone will not allow and restrict traffic as required without firewall rules.",
      B:"This adds complexity to the architecture and the instance configuration.",
      C:"Routes still require firewall rules to allow traffic; tags define which instances a route applies to, not the next hop.",
      D:"As instances scale they share the same tag per tier; tags can be used for both target and source in firewall rules to allow and restrict traffic."} },

  { id:16, topic:"Security & Compliance", case:null, type:"single",
    text:"You are designing a large distributed application with 30 microservices. Each microservice needs to connect to a database backend. You want to store the credentials securely. Where should you store the credentials?",
    options:{ A:"In the source code", B:"In an environment variable",
      C:"In a secret management system", D:"In a config file that has restricted access through ACLs"},
    correct:["C"],
    why:{ A:"Credentials in source code are discoverable in plain text by anyone with source access, and require redeploys on rotation.",
      B:"Consistently populating environment variables requires the credentials available, in plain text, when the session starts.",
      C:"A secret management system such as Secret Manager is a secure central store and single source of truth to manage, access, and audit secrets across Google Cloud.",
      D:"A key management system is better than manually managing a config file; a plaintext config file also increases risk."} },

  { id:17, topic:"Security & Compliance", case:null, type:"single",
    text:"Your customer is moving corporate applications to Google Cloud. The security team wants detailed visibility of all resources in the organization. You set yourself up as the Organization Administrator. Which IAM roles should you give to the security team while following Google-recommended practices?",
    options:{ A:"Organization viewer, Project owner", B:"Organization viewer, Project viewer",
      C:"Organization administrator, Project browser", D:"Project owner, Network administrator"},
    correct:["B"],
    why:{ A:"Project owner is too broad — the security team does not need to make changes to projects.",
      B:"Organization viewer grants permission to view the organization's display name, and Project viewer grants permission to see the resources within projects.",
      C:"Organization Administrator is too broad — the team does not need to change the organization.",
      D:"Project Owner is too broad — the team does not need to change projects."} },

  { id:18, topic:"Cost & Optimization", case:null, type:"multi", pick:2,
    text:"To reduce costs, all developers must move their development infrastructure from on-premises VMs to Google Cloud. These resources go through multiple start/stop events during the day and require state to persist. You must design the process of running a development environment in Google Cloud while providing cost visibility to the finance department. Which two steps should you take? (Choose two)",
    options:{ A:"Use persistent disks to store the state. Start and stop the VM as needed.",
      B:"Use the \"gcloud --auto-delete\" flag on all persistent disks before stopping the VM.",
      C:"Apply VM CPU utilization label and include it in the BigQuery billing export.",
      D:"Use BigQuery billing export and labels to relate cost to groups.",
      E:"Store all state in a Local SSD, snapshot the persistent disks, and terminate the VM."},
    correct:["A","D"],
    why:{ A:"Persistent disks will not be deleted when an instance is stopped.",
      B:"The --auto-delete flag has no effect unless the instance is deleted; stopping does not delete the instance or its disks.",
      C:"Labels are used to organize instances, not to monitor metrics.",
      D:"Exporting daily usage and cost estimates to a BigQuery dataset provides visibility to finance; labels then group costs by team or cost center.",
      E:"State stored in local SSDs will be lost when the instance is stopped."} },

  { id:19, topic:"Compute & Storage", case:null, type:"single",
    text:"The database team asks you to improve the performance of their new database server on Compute Engine, used for importing and normalizing performance statistics. It is MySQL on Debian Linux, on an n1-standard-8 VM with 80 GB of SSD zonal persistent disk, which they can't restart until the next maintenance event. What should they change to get better performance as soon as possible and cost-effectively?",
    options:{ A:"Increase the virtual machine's memory to 64 GB.",
      B:"Create a new virtual machine running PostgreSQL.",
      C:"Dynamically resize the SSD persistent disk to 500 GB.",
      D:"Migrate their performance metrics warehouse to BigQuery."},
    correct:["C"],
    why:{ A:"Increasing the memory size requires a VM restart.",
      B:"The team wants help with MySQL; migrating products shouldn't be the answer when other optimizations remain.",
      C:"Persistent disk performance scales with total disk capacity and the instance's vCPU count; increasing capacity increases throughput and IOPS, improving MySQL performance — and a PD can be resized without a restart.",
      D:"The team wants help with MySQL; migrating products shouldn't be the answer when other optimizations remain."} },
];
